/* Training Academy course pages — content. All copy is original.
   Facts used: CPD-certified provider, QUALIFI Levels 4/5/7 offered, ProQual L3,
   OFQUAL-regulated L3 diploma route, hands-on practice on live models under the
   direct supervision of a registered doctor, working W1 clinic. */

const enrolSteps = (practical) => [
  ['Enquire and check suitability', 'Tell us your background and goal. We confirm the right course and entry route for you honestly, including recommending a different starting point if that serves you better.'],
  ['Theory, properly taught', 'Structured study of the science behind the procedure: anatomy, product knowledge, indications, contraindications and complication management, so your hands are guided by understanding.'],
  ['Supervised practice on live models', practical],
  ['Assessment and certification', 'Your competence is assessed before you certify, and you leave with the LCA certificate for your course and a clear path for what to train in next.'],
];

export const courses = [
  {
    slug: 'dermal-filler-foundation',
    kickerTag: 'CPD Course · Foundation',
    title: 'Dermal Filler Foundation',
    lede: 'Your entry into injectables, taught the clinical way: anatomy first, product knowledge second, needles third, and all of it under the eye of a registered doctor.',
    metaDesc: 'Foundation dermal filler training in London W1. CPD-accredited, hands-on practice on live models under the direct supervision of a registered doctor.',
    icon: 'droplet',
    tint: 'rgba(176,116,92,.34)',
    img: 'course-dermal-filler-foundation.jpg',
    imgAlt: 'Dermal filler foundation training at the LCA Academy',
    about: [
      'The Dermal Filler Foundation course is where safe injectors are made. It exists for one reason: to take you from theory to your first confident, supervised filler treatments without skipping the parts that make the difference between a technician and a practitioner.',
      'Training happens inside our <strong>working Marylebone clinic</strong>, not a hired hotel room. You learn where real treatments happen, with the equipment, hygiene standards and client flow of a genuine practice around you.',
      'Most importantly, your practical work is done on <strong>live models under the direct supervision of a registered doctor</strong>. You will be corrected in the moment, questioned on your reasoning and signed off only when your technique deserves it.',
    ],
    coverIntro: 'The syllabus balances the science you must know with the hands-on skill you came for.',
    covers: [
      '<strong>Facial anatomy for injectors:</strong> vasculature, danger zones and the layers where filler lives',
      '<strong>Hyaluronic acid products:</strong> how fillers differ, and how to choose responsibly',
      '<strong>Consultation and consent:</strong> assessing suitability and setting honest expectations',
      '<strong>Core techniques:</strong> needle handling, depth, placement and dosing for foundation areas such as lips and nasolabial folds',
      '<strong>Complication awareness:</strong> recognising, managing and escalating, before you ever need to',
      '<strong>Aftercare and record-keeping:</strong> the professional habits that protect clients and careers',
    ],
    steps: enrolSteps('Foundation injection techniques performed on volunteer models in our W1 clinic, one-to-one with the supervising doctor beside you, until each technique is demonstrably yours.'),
    accreditation: [
      'This is a <strong>CPD-accredited</strong> course delivered by London Classic Aesthetics, a registered clinic and recognised training provider. Your certificate documents both the theory and the supervised practical elements you completed.',
      'The LCA certificate is designed to support practice beyond the UK, and many of our courses form stepping stones toward regulated qualifications, including OFQUAL-regulated and QUALIFI routes at Levels 4 to 7 that we deliver.',
    ],
    faqs: [
      ['Do I need a medical background to start?', 'The foundation course welcomes both healthcare professionals and committed non-medics, and the entry route differs by background. Tell us yours when you enquire and we will map the correct pathway, honestly.'],
      ['Will I really inject on the day?', 'Yes. Supervised practice on live models is the heart of the course. You will not leave having only watched.'],
      ['Who supervises the practical work?', 'A registered doctor supervises directly, in the room, correcting technique as you work. That level of oversight is the reason students choose LCA.'],
      ['What can I do after the course?', 'You leave able to perform foundation filler treatments within your scope of practice, with a CPD certificate documenting your training, and a clear recommendation for your next step, typically the Advanced Dermal Filler course.'],
      ['How do I secure a place?', 'Enquire through the contact page or email us with the course name. We confirm suitability, then dates and enrolment details directly.'],
    ],
    rail: [
      ['Level', 'Foundation, CPD-accredited'],
      ['Format', 'Theory plus supervised hands-on practice'],
      ['Models', 'Live volunteer models provided'],
      ['Supervision', 'Direct, by a registered doctor'],
      ['Setting', 'Working clinic, 157 Seymour Place, W1'],
    ],
    related: [
      ['academy/advanced-dermal-filler.html', 'Next step', 'Advanced Dermal Filler'],
      ['academy/anatomy-physiology.html', 'Foundation', 'Anatomy & Physiology'],
      ['academy/skin-booster.html', 'Add a skill', 'Skin Booster Course'],
    ],
    ctaTitle: 'Learn to inject the way doctors are taught.',
    ctaLede: 'Enquire about the Dermal Filler Foundation course and start your aesthetics career with supervision worth the name.',
  },

  {
    slug: 'advanced-dermal-filler',
    kickerTag: 'CPD Course · Advanced',
    title: 'Advanced Dermal Filler',
    lede: 'For practitioners ready to move beyond safe basics: cheeks, jawline, chin and non-surgical rhinoplasty, with cannula work and complication management to match.',
    metaDesc: 'Advanced dermal filler training in London W1: cheek, jaw, chin, tear trough and non-surgical rhinoplasty techniques, supervised by a registered doctor.',
    icon: 'droplet',
    tint: 'rgba(160,100,70,.36)',
    img: 'course-advanced-dermal-filler.jpg',
    imgAlt: 'Advanced dermal filler training at the LCA Academy',
    about: [
      'Foundation training teaches you to treat safely. The Advanced Dermal Filler course teaches you to treat <strong>ambitiously and still safely</strong>: full-face assessment, structural areas, cannula technique and the judgement that separates practitioners clients trust with their faces.',
      'The areas covered here, cheeks, jawline, chin, tear troughs and the nose, are where reputations are built and where anatomy demands respect. Accordingly, the ratio of supervision to student stays uncompromisingly high.',
      'As with all LCA practical training, you work on live models in our W1 clinic under the direct supervision of a registered doctor, with your technique challenged and refined case by case.',
    ],
    coverIntro: 'The syllabus assumes competence and builds mastery.',
    covers: [
      '<strong>Full-face assessment:</strong> planning treatments that balance features rather than chase single areas',
      '<strong>Structural augmentation:</strong> cheek, chin and jawline techniques for shape that holds',
      '<strong>Tear trough treatment:</strong> patient selection and technique for the least forgiving area in aesthetics',
      '<strong>Non-surgical rhinoplasty:</strong> precision work in a high-stakes zone, taught with appropriate gravity',
      '<strong>Cannula technique:</strong> when and how to trade needle precision for cannula safety',
      '<strong>Complication management:</strong> vascular events, hyaluronidase protocols and emergency readiness',
    ],
    steps: enrolSteps('Advanced techniques performed on live models with the supervising doctor at your shoulder: structural areas, cannula work and full-face planning, signed off case by case.'),
    accreditation: [
      'A <strong>CPD-accredited</strong> advanced course from a registered clinic and training provider, documenting supervised competence in advanced filler techniques.',
      'For practitioners building a formal portfolio, this course sits naturally alongside our regulated routes, including OFQUAL-regulated study and QUALIFI qualifications at Levels 4 to 7.',
    ],
    faqs: [
      ['What do I need before enrolling?', 'Foundation-level filler training and genuine injecting confidence. If you trained elsewhere, tell us your background at enquiry; we assess suitability honestly and will recommend the foundation course first if the gap is real.'],
      ['Is non-surgical rhinoplasty really teachable on this course?', 'Yes, and it is taught with the seriousness it deserves: patient selection, anatomy, technique and complication protocol, practised under direct doctor supervision.'],
      ['Why does cannula technique matter?', 'In several advanced areas a cannula meaningfully reduces vascular risk. Knowing when to use which tool is exactly the judgement this course develops.'],
      ['How are complications covered?', 'As a full module, not a footnote: recognition, hyaluronidase use, escalation and prevention. Advanced practice means being prepared for the day you hope never comes.'],
      ['What comes after this course?', 'Many practitioners add PDO threads or skin boosters to broaden their menu, or progress toward regulated qualifications. We will advise based on where you want your practice to go.'],
    ],
    rail: [
      ['Level', 'Advanced, CPD-accredited'],
      ['Prerequisite', 'Foundation filler training, checked at enquiry'],
      ['Format', 'Theory plus supervised live-model practice'],
      ['Supervision', 'Direct, by a registered doctor'],
      ['Setting', 'Working clinic, 157 Seymour Place, W1'],
    ],
    related: [
      ['academy/pdo-threads.html', 'Broaden', 'PDO Threads Course'],
      ['academy/dermal-filler-foundation.html', 'Start here', 'Dermal Filler Foundation'],
      ['academy/ofqual-level-3-diploma.html', 'Go regulated', 'OFQUAL Level 3 Diploma'],
    ],
    ctaTitle: 'Advance your hands and your judgement.',
    ctaLede: 'Enquire about Advanced Dermal Filler training and take on the areas that build serious practices, with serious supervision.',
  },

  {
    slug: 'skin-booster',
    kickerTag: 'CPD Course',
    title: 'Skin Booster Course',
    lede: 'Train in the treatment clients increasingly ask for by name: injectable hydration that improves skin quality rather than shape.',
    metaDesc: 'Skin booster training in London W1: CPD-accredited course covering injectable hydration treatments, with live-model practice under doctor supervision.',
    icon: 'droplet',
    tint: 'rgba(190,160,110,.32)',
    img: 'course-skin-booster.jpg',
    imgAlt: 'Skin booster training at the LCA Academy',
    about: [
      'Skin boosters are one of the fastest growing requests in clinics: micro-depots of soft hyaluronic acid placed into the skin itself, for hydration, elasticity and glow that skincare cannot reach. Clients love them because they look like themselves, only better rested.',
      'This CPD course teaches the treatment end to end: product selection, injection patterns, dosing and the client conversations that keep expectations honest, since boosters improve quality, not volume.',
      'Practical training runs on live models in our Marylebone clinic under the direct supervision of a registered doctor, so your technique is corrected where it counts: in the moment.',
    ],
    coverIntro: 'A tight, practical syllabus you can add to your menu immediately.',
    covers: [
      '<strong>The science of skin quality:</strong> what boosters do in the dermis, and what they honestly cannot',
      '<strong>Products and protocols:</strong> choosing between booster formulations responsibly',
      '<strong>Injection technique:</strong> patterns, depth and dosing for face and beyond',
      '<strong>Client selection:</strong> who will love the result, and who needs a different plan',
      '<strong>Course design:</strong> structuring multi-session treatment plans and maintenance',
      '<strong>Aftercare and complications:</strong> managing the predictable and preparing for the rare',
    ],
    steps: enrolSteps('Booster techniques practised on live models: mapping, injection patterns and dosing, refined under the supervising doctor until consistent.'),
    accreditation: [
      'CPD-accredited and delivered by a registered clinic and training provider, with your certificate covering both theory and supervised practical work.',
      'Boosters pair naturally with our mesotherapy and filler training if you are building a complete skin-quality offering, and progress routes exist to regulated qualifications.',
    ],
    faqs: [
      ['Who is this course for?', 'Practitioners with injection fundamentals who want to add a high-demand, lower-risk treatment to their menu. Backgrounds are checked at enquiry and we advise honestly on readiness.'],
      ['How is this different from mesotherapy training?', 'Related skills, different treatments: mesotherapy delivers nutrient blends superficially, boosters deposit hyaluronic acid for deep hydration. Many practitioners train in both; we will happily map the pairing for you.'],
      ['Will I practise on real people?', 'Yes, on volunteer live models in our working clinic, supervised directly by a registered doctor.'],
      ['Do clients actually ask for this?', 'Increasingly by brand name. Skin quality treatments are among the strongest growth areas in UK aesthetics, and boosters sit at the centre of that demand.'],
      ['How do I enrol?', 'Enquire via the contact page or email with the course name; we confirm suitability and share upcoming dates directly.'],
    ],
    rail: [
      ['Level', 'CPD-accredited'],
      ['Format', 'Theory plus supervised live-model practice'],
      ['Focus', 'Injectable skin hydration and quality'],
      ['Supervision', 'Direct, by a registered doctor'],
      ['Setting', 'Working clinic, 157 Seymour Place, W1'],
    ],
    related: [
      ['academy/mesotherapy-course.html', 'Pairs with', 'Mesotherapy Course'],
      ['academy/dermal-filler-foundation.html', 'Foundation', 'Dermal Filler Foundation'],
      ['academy/chemical-peel.html', 'Add a skill', 'Chemical Peel Course'],
    ],
    ctaTitle: 'Teach your hands the glow treatment.',
    ctaLede: 'Enquire about the Skin Booster course and add the skin-quality treatment modern clients actively search for.',
  },

  {
    slug: 'pdo-threads',
    kickerTag: 'CPD Course · Advanced',
    title: 'PDO Threads Course',
    lede: 'Learn thread lifting properly: patient selection, vector planning and placement technique for the non-surgical lift, under direct doctor supervision.',
    metaDesc: 'PDO thread lift training in London W1: CPD-accredited advanced course with live-model practice supervised by a registered doctor.',
    icon: 'thread',
    tint: 'rgba(150,120,80,.34)',
    img: 'course-pdo-threads.jpg',
    imgAlt: 'PDO threads training at the LCA Academy',
    about: [
      'PDO threads occupy a distinct place in aesthetics: the treatment for clients who want lift, not volume, without surgery. Dissolvable threads reposition and support tissue while stimulating collagen along their path.',
      'It is also a treatment where training quality is instantly visible in results, which is why this course is unhurried about fundamentals: facial vectors, thread selection, insertion planes and the honest limits of what threads can lift.',
      'Practical sessions run on live models in our W1 clinic under the direct supervision of a registered doctor, with each placement reviewed as you work.',
    ],
    coverIntro: 'A syllabus built around judgement as much as technique.',
    covers: [
      '<strong>Thread types and behaviour:</strong> mono, screw and cog threads, and what each is actually for',
      '<strong>Patient selection:</strong> reading tissue quality and knowing when threads will disappoint',
      '<strong>Vector planning:</strong> mapping lift direction for natural, balanced results',
      '<strong>Insertion technique:</strong> planes, entry points and placement, practised under supervision',
      '<strong>Combining treatments:</strong> where threads meet fillers and toxin in a full-face plan',
      '<strong>Complications:</strong> prevention, recognition and management, covered without euphemism',
    ],
    steps: enrolSteps('Thread placement practised on live models: planning vectors, marking, insertion and review, with the supervising doctor guiding every case.'),
    accreditation: [
      'CPD-accredited advanced training from a registered clinic and training provider, documenting supervised practical competence in thread lifting.',
      'For practitioners assembling a complete non-surgical lifting portfolio, this course pairs naturally with Advanced Dermal Filler training and our regulated qualification routes.',
    ],
    faqs: [
      ['What experience do I need first?', 'This is an advanced course: injecting experience and sound facial anatomy are expected. Your background is reviewed at enquiry, and we will be straight with you if foundation work should come first.'],
      ['Are threads difficult to learn?', 'They demand planning discipline more than dexterity. The technique is teachable; the judgement about who, where and how much is what this course drills, deliberately.'],
      ['What models will I work on?', 'Volunteer live models treated in our working clinic, under direct doctor supervision, exactly as your future clients will be.'],
      ['Do threads replace filler?', 'No; they answer a different problem. Threads reposition, fillers restore volume. Knowing which a face needs is a core outcome of this training.'],
      ['How do I book a place?', 'Enquire with your background and the course name via the contact page or email; suitability and dates are confirmed personally.'],
    ],
    rail: [
      ['Level', 'Advanced, CPD-accredited'],
      ['Prerequisite', 'Injecting experience, checked at enquiry'],
      ['Format', 'Theory plus supervised live-model practice'],
      ['Supervision', 'Direct, by a registered doctor'],
      ['Setting', 'Working clinic, 157 Seymour Place, W1'],
    ],
    related: [
      ['academy/advanced-dermal-filler.html', 'Pairs with', 'Advanced Dermal Filler'],
      ['academy/prp.html', 'Add a skill', 'PRP Course'],
      ['academy/index.html', 'Overview', 'All courses'],
    ],
    ctaTitle: 'Add lift to your repertoire.',
    ctaLede: 'Enquire about PDO thread training and learn the non-surgical lift with the supervision this technique demands.',
  },

  {
    slug: 'mesotherapy-course',
    kickerTag: 'CPD Course',
    title: 'Mesotherapy Course',
    lede: 'Master micro-injection therapy for skin quality and hair support: cocktails, techniques and treatment planning, taught in a working clinic.',
    metaDesc: 'Mesotherapy training in London W1: CPD-accredited course covering skin and scalp micro-injection techniques with supervised live-model practice.',
    icon: 'face',
    tint: 'rgba(146,142,84,.30)',
    img: 'course-mesotherapy.jpg',
    imgAlt: 'Mesotherapy training at the LCA Academy',
    about: [
      'Mesotherapy is the quiet workhorse of aesthetic practice: micro-injections of vitamins, minerals and hyaluronic acid that improve skin quality and support thinning hair. It builds loyal, returning clients precisely because it is gentle, honest and cumulative.',
      'This CPD course covers the full treatment: formulations and what is actually in them, injection patterns and depths for face and scalp, and the course-based treatment planning that makes mesotherapy commercially sensible.',
      'You practise on live models in our Marylebone clinic under the direct supervision of a registered doctor, building speed and consistency with real feedback.',
    ],
    coverIntro: 'From vial to treatment plan, nothing assumed.',
    covers: [
      '<strong>Mesotherapy science:</strong> how micro-dosing into the dermis differs from topical and systemic routes',
      '<strong>Cocktails and formulations:</strong> reading ingredient lists critically and choosing suppliers responsibly',
      '<strong>Facial technique:</strong> patterns, depth control and dosing for hydration and radiance',
      '<strong>Scalp technique:</strong> supporting weakening follicles, and setting honest expectations for hair work',
      '<strong>Treatment course design:</strong> sessions, spacing and maintenance that clients understand and keep',
      '<strong>Hygiene, aftercare and records:</strong> the professional standards that make gentle treatments safe',
    ],
    steps: enrolSteps('Facial and scalp mesotherapy practised on live models, with pattern, depth and pace corrected in real time by the supervising doctor.'),
    accreditation: [
      'CPD-accredited and delivered by a registered clinic and training provider; your certificate records both theory and supervised practical elements.',
      'Mesotherapy pairs commercially with skin boosters and chemical peels, and we will happily map a multi-course pathway if you are building a full skin practice.',
    ],
    faqs: [
      ['Is this a beginner-friendly course?', 'It is among the most accessible injection courses we teach, and entry depends on background. Enquire with yours and we will confirm the right route honestly.'],
      ['Does it cover hair treatments too?', 'Yes; scalp mesotherapy is taught alongside facial work, including the client conversations about what follicle support can and cannot achieve.'],
      ['What will I practise on?', 'Volunteer live models in our working W1 clinic, under the direct supervision of a registered doctor.'],
      ['Why do clinics rate mesotherapy commercially?', 'Because it is course-based and maintenance-friendly: clients return on a rhythm, results build visibly, and it introduces clients gently to wider treatments.'],
      ['How do I enrol?', 'Send an enquiry with the course name through the contact page or by email, and we will confirm suitability and dates personally.'],
    ],
    rail: [
      ['Level', 'CPD-accredited'],
      ['Format', 'Theory plus supervised live-model practice'],
      ['Focus', 'Facial and scalp micro-injection therapy'],
      ['Supervision', 'Direct, by a registered doctor'],
      ['Setting', 'Working clinic, 157 Seymour Place, W1'],
    ],
    related: [
      ['academy/skin-booster.html', 'Pairs with', 'Skin Booster Course'],
      ['academy/chemical-peel.html', 'Add a skill', 'Chemical Peel Course'],
      ['services/mesotherapy.html', 'See it offered', 'Mesotherapy in clinic'],
    ],
    ctaTitle: 'The workhorse skill, done properly.',
    ctaLede: 'Enquire about mesotherapy training and add a treatment clients return for, taught with clinical discipline.',
  },

  {
    slug: 'prp',
    kickerTag: 'CPD Course',
    title: 'Platelet-Rich Plasma (PRP) Course',
    lede: 'Train in regenerative treatment using the client’s own blood: draw, spin, prepare and reinject, taught end to end with clinical rigour.',
    metaDesc: 'PRP training in London W1: CPD-accredited course covering blood draw, centrifugation, preparation and injection technique for skin and hair.',
    icon: 'vial',
    tint: 'rgba(165,95,80,.32)',
    img: 'course-prp.jpg',
    imgAlt: 'PRP training at the LCA Academy',
    about: [
      'Platelet-rich plasma sits apart from other aesthetic treatments: nothing synthetic is injected at all. The client’s own blood is drawn, spun to concentrate the platelets, and returned to skin or scalp where those growth factors support repair and renewal.',
      'Because PRP spans venepuncture, laboratory handling and injection technique, it is genuinely multi-skill training, and this course teaches every link in that chain rather than assuming any of them.',
      'As always at LCA, the practical work happens on live models in our W1 clinic under the direct supervision of a registered doctor, from first draw to final injection.',
    ],
    coverIntro: 'Every stage of the PRP workflow, taught in order.',
    covers: [
      '<strong>The science of PRP:</strong> platelets, growth factors and the honest evidence picture',
      '<strong>Venepuncture:</strong> safe, confident blood draws (building on phlebotomy fundamentals)',
      '<strong>Preparation:</strong> centrifugation, handling and maintaining a sterile chain',
      '<strong>Facial application:</strong> injection and micro-needling-assisted techniques for skin quality',
      '<strong>Scalp application:</strong> PRP for thinning hair, with realistic outcome-setting',
      '<strong>Protocols and safety:</strong> screening, contraindications, aftercare and records',
    ],
    steps: enrolSteps('The full PRP workflow practised on live models: draw, spin, prepare and treat, with the supervising doctor overseeing each stage.'),
    accreditation: [
      'CPD-accredited training from a registered clinic and training provider, documenting the complete supervised workflow rather than the injection alone.',
      'PRP pairs naturally with our Phlebotomy course for those newer to blood draws, and with mesotherapy for a complete regenerative skin-and-hair offering.',
    ],
    faqs: [
      ['Do I need to know how to take blood first?', 'It helps but is not assumed: venepuncture is taught within the course, and our dedicated Phlebotomy course exists if you want deeper grounding first. We will advise honestly at enquiry.'],
      ['Is PRP evidence-based?', 'PRP has a genuine and growing evidence base, strongest in certain applications, and this course teaches you to represent that picture honestly to clients rather than oversell it.'],
      ['What equipment will I learn on?', 'Clinical centrifuge and preparation systems of the kind used in practice, inside our working clinic, so nothing on your first solo day feels unfamiliar.'],
      ['Face, hair, or both?', 'Both applications are covered, including how to select candidates for each and set expectations that survive contact with reality.'],
      ['How do I secure a place?', 'Enquire via the contact page or email with the course name; suitability and dates are confirmed personally.'],
    ],
    rail: [
      ['Level', 'CPD-accredited'],
      ['Format', 'Full workflow: draw, prepare, treat'],
      ['Focus', 'Regenerative skin and hair treatment'],
      ['Supervision', 'Direct, by a registered doctor'],
      ['Setting', 'Working clinic, 157 Seymour Place, W1'],
    ],
    related: [
      ['academy/phlebotomy.html', 'Foundation', 'Phlebotomy Course'],
      ['academy/mesotherapy-course.html', 'Pairs with', 'Mesotherapy Course'],
      ['academy/iv-therapy.html', 'Add a skill', 'IV Therapy Course'],
    ],
    ctaTitle: 'Regenerative skills, end to end.',
    ctaLede: 'Enquire about PRP training and learn the complete workflow, not just the final syringe.',
  },

  {
    slug: 'iv-therapy',
    kickerTag: 'CPD Course',
    title: 'Intravenous Therapy Course',
    lede: 'Cannulation, infusion protocols and client safety for the booming IV wellness sector, taught by a clinic that runs drips daily.',
    metaDesc: 'IV therapy training in London W1: CPD-accredited course in cannulation, vitamin infusion protocols and client screening, with supervised practice.',
    icon: 'drip',
    tint: 'rgba(180,150,90,.34)',
    img: 'course-iv-therapy.jpg',
    imgAlt: 'IV therapy training at the LCA Academy',
    about: [
      'IV vitamin therapy has grown from niche to mainstream, and the sector needs practitioners trained to clinical standards rather than weekend-workshop shortcuts. This course teaches intravenous therapy the way it is practised in our own clinic: screened, sterile and unhurried.',
      'The skill at the centre is <strong>cannulation</strong>: placing intravenous access confidently and kindly. Around it sit the equally important skills of screening clients, selecting formulations honestly and running infusions safely from setup to sign-off.',
      'You train inside a clinic that delivers IV drips as a live service, under the direct supervision of a registered doctor, so protocols are demonstrated where they are actually used.',
    ],
    coverIntro: 'Clinical technique first, wellness menu second.',
    covers: [
      '<strong>Vascular anatomy and site selection:</strong> choosing veins well, and what to do when they hide',
      '<strong>Cannulation technique:</strong> insertion, securing and removal, practised until calm',
      '<strong>Infusion protocols:</strong> rates, monitoring and documentation from start to finish',
      '<strong>Screening and contraindications:</strong> who should not receive a drip, and how to say so',
      '<strong>Formulation literacy:</strong> what is actually in vitamin infusions, and honest client conversations',
      '<strong>Emergencies and complications:</strong> recognising and responding, before it is ever needed',
    ],
    steps: enrolSteps('Cannulation and infusion practice on live models under direct doctor supervision, repeated until your technique is smooth and your protocol automatic.'),
    accreditation: [
      'CPD-accredited and taught by a registered clinic and training provider that runs IV therapy as a daily service, not a demonstration.',
      'This course pairs directly with Phlebotomy for complete vascular access skills, and with PRP where blood handling meets aesthetics.',
    ],
    faqs: [
      ['Who is this course designed for?', 'Healthcare professionals extending their scope and practitioners entering the IV wellness sector. Backgrounds and entry routes are confirmed honestly at enquiry.'],
      ['Will I cannulate real people?', 'Yes, under direct supervision by a registered doctor, with technique corrected in the moment. Confidence comes from real veins, respectfully practised on.'],
      ['What is covered about the drips themselves?', 'Formulation literacy is a full module: what common vitamin infusions contain, what the evidence supports, and how to advise clients without inflating claims.'],
      ['How does this differ from phlebotomy training?', 'Phlebotomy is drawing blood out; IV therapy is delivering fluids in, with infusion management around it. The skills are siblings, and many students take both.'],
      ['How do I enrol?', 'Enquire through the contact page or email with the course name, and we will confirm suitability and upcoming dates.'],
    ],
    rail: [
      ['Level', 'CPD-accredited'],
      ['Format', 'Theory plus supervised cannulation practice'],
      ['Focus', 'Cannulation, infusion protocols, screening'],
      ['Supervision', 'Direct, by a registered doctor'],
      ['Setting', 'Working clinic, 157 Seymour Place, W1'],
    ],
    related: [
      ['academy/phlebotomy.html', 'Pairs with', 'Phlebotomy Course'],
      ['academy/prp.html', 'Add a skill', 'PRP Course'],
      ['services/iv-drips.html', 'See it offered', 'IV Drips in clinic'],
    ],
    ctaTitle: 'Learn IV therapy where it is practised.',
    ctaLede: 'Enquire about IV therapy training and enter the wellness sector with genuinely clinical hands.',
  },

  {
    slug: 'phlebotomy',
    kickerTag: 'CPD Course',
    title: 'Phlebotomy Course',
    lede: 'The foundational clinical skill of drawing blood: anatomy, technique and professionalism, taught hands-on in a working London clinic.',
    metaDesc: 'Phlebotomy training in London W1: CPD-accredited hands-on venepuncture course with supervised practice, suitable for clinical and aesthetic careers.',
    icon: 'vial',
    tint: 'rgba(140,110,90,.32)',
    img: 'course-phlebotomy.jpg',
    imgAlt: 'Phlebotomy training at the LCA Academy',
    about: [
      'Phlebotomy is one of the most employable clinical skills in Britain: hospitals, GP surgeries, private clinics, research and the aesthetics sector all need people who can draw blood competently and kindly.',
      'This course takes you from vascular anatomy to confident venepuncture: equipment, order of draw, technique, difficult veins and the calm professional manner that patients remember.',
      'Training is hands-on in our Marylebone clinic under the direct supervision of a registered doctor, because needle confidence is built with real practice, not slides.',
    ],
    coverIntro: 'Everything a competent phlebotomist relies on, in teaching order.',
    covers: [
      '<strong>Vascular anatomy:</strong> vein selection, palpation and the sites to avoid',
      '<strong>Equipment fluency:</strong> needles, vacutainers, butterflies and when each earns its place',
      '<strong>Venepuncture technique:</strong> insertion angle, anchoring and smooth, low-pain draws',
      '<strong>Order of draw and labelling:</strong> the details that make samples usable and audits painless',
      '<strong>Difficult draws:</strong> fragile, rolling and reluctant veins, handled without drama',
      '<strong>Safety and professionalism:</strong> sharps, infection control, consent and patient care',
    ],
    steps: enrolSteps('Supervised venepuncture practice on live models, repeated with correction until your draws are smooth, safe and confident.'),
    accreditation: [
      'CPD-accredited training delivered by a registered clinic and training provider, with certification documenting supervised practical competence.',
      'Phlebotomy is the natural first step toward our IV Therapy and PRP courses, where vascular access becomes the gateway to wider practice.',
    ],
    faqs: [
      ['Do I need any medical background?', 'No prior clinical career is assumed; the course is built to take committed beginners to competence. Your background simply shapes the pace, and we confirm fit at enquiry.'],
      ['Will I take blood from real people?', 'Yes, under the direct supervision of a registered doctor. Simulation has its place, but competence and confidence come from real, supervised draws.'],
      ['Where can this skill take me?', 'NHS and private healthcare support roles, clinics, research settings, and onward into IV therapy and PRP work within aesthetics. It is a genuinely door-opening certificate.'],
      ['I am nervous around needles. Can I still learn?', 'Very often, yes; handling needles professionally is different from receiving them, and structured practice steadily replaces nerves with method. Be honest with us at enquiry and we will support you properly.'],
      ['How do I enrol?', 'Send an enquiry with the course name via the contact page or email, and suitability and dates will be confirmed personally.'],
    ],
    rail: [
      ['Level', 'CPD-accredited, beginner-friendly'],
      ['Format', 'Theory plus supervised venepuncture practice'],
      ['Focus', 'Safe, confident blood draws'],
      ['Supervision', 'Direct, by a registered doctor'],
      ['Setting', 'Working clinic, 157 Seymour Place, W1'],
    ],
    related: [
      ['academy/iv-therapy.html', 'Next step', 'IV Therapy Course'],
      ['academy/prp.html', 'Next step', 'PRP Course'],
      ['academy/anatomy-physiology.html', 'Foundation', 'Anatomy & Physiology'],
    ],
    ctaTitle: 'Start with the skill everything builds on.',
    ctaLede: 'Enquire about phlebotomy training and gain a clinical skill with immediate, practical career value.',
  },

  {
    slug: 'chemical-peel',
    kickerTag: 'CPD Course',
    title: 'Chemical Peel Course',
    lede: 'From superficial refreshers to deeper resurfacing: acids, depths, skin types and the judgement to match them, taught hands-on.',
    metaDesc: 'Chemical peel training in London W1: CPD-accredited course covering peel chemistry, skin assessment and application technique with supervised practice.',
    icon: 'face',
    tint: 'rgba(196,150,80,.32)',
    img: 'course-chemical-peel.jpg',
    imgAlt: 'Chemical peel training at the LCA Academy',
    about: [
      'Chemical peels are deceptively simple: an acid, a brush, a timer. The craft is in everything around that, reading skin, choosing depth, managing expectations and knowing precisely when a peel is the wrong answer. That judgement is what this course teaches.',
      'You will learn the chemistry without the chemistry degree: AHAs, BHAs and blended peels, what each depth genuinely achieves, and how skin type changes every decision, including when to decline.',
      'Application technique is practised on live models in our W1 clinic under the direct supervision of a registered doctor, from preparation and timing to neutralising and aftercare.',
    ],
    coverIntro: 'Chemistry, judgement and hands, in that order.',
    covers: [
      '<strong>Peel chemistry made usable:</strong> AHAs, BHAs, TCA and blends, without mystique',
      '<strong>Depth and outcome:</strong> superficial to deeper peels, and what each honestly delivers',
      '<strong>Skin assessment:</strong> Fitzpatrick types, contraindications and pre-peel preparation',
      '<strong>Application technique:</strong> coverage, timing, layering and endpoints, practised live',
      '<strong>Managing the peel journey:</strong> what clients experience day by day, and how to guide it',
      '<strong>Complications and correction:</strong> pigmentation risks and how professionals prevent them',
    ],
    steps: enrolSteps('Peel preparation, application, timing and neutralising practised on live models, with the supervising doctor guiding depth decisions case by case.'),
    accreditation: [
      'CPD-accredited and taught by a registered clinic and training provider, with certification covering theory and supervised application.',
      'Peels pair commercially with mesotherapy and skin boosters as a complete skin-quality menu, and progression routes exist to regulated qualifications.',
    ],
    faqs: [
      ['Is this course suitable for beginners?', 'Peels are an accessible entry into clinical skin treatments, and entry depends on background: beauticians, aestheticians and healthcare professionals each have a route. We confirm yours at enquiry.'],
      ['Which peels will I be able to offer afterwards?', 'The course centres on the superficial-to-medium range where safe independent practice lives, with deeper work covered so you understand the full landscape and refer wisely.'],
      ['How is darker skin covered?', 'Thoroughly; peel selection by skin type, pigmentation risk and preparation protocols are core modules, not asides. Treating all skin tones safely is non-negotiable.'],
      ['Will I practise on live models?', 'Yes, in our working Marylebone clinic under direct doctor supervision.'],
      ['How do I enrol?', 'Enquire through the contact page or email with the course name; we will confirm suitability and share dates personally.'],
    ],
    rail: [
      ['Level', 'CPD-accredited'],
      ['Format', 'Theory plus supervised live-model practice'],
      ['Focus', 'Peel chemistry, assessment, application'],
      ['Supervision', 'Direct, by a registered doctor'],
      ['Setting', 'Working clinic, 157 Seymour Place, W1'],
    ],
    related: [
      ['academy/mesotherapy-course.html', 'Pairs with', 'Mesotherapy Course'],
      ['academy/skin-booster.html', 'Pairs with', 'Skin Booster Course'],
      ['academy/facial-electrotherapy.html', 'Go regulated', 'Facial Electrotherapy · ProQual L3'],
    ],
    ctaTitle: 'Resurface skin with real judgement.',
    ctaLede: 'Enquire about chemical peel training and learn the treatment where reading skin matters as much as applying acid.',
  },

  {
    slug: 'facial-electrotherapy',
    kickerTag: 'Regulated · ProQual Level 3',
    title: 'ProQual Level 3 Certificate in Facial Electrotherapy',
    lede: 'A regulated Level 3 qualification in machine-based facial treatments: the recognised stepping stone toward advanced aesthetic practice.',
    metaDesc: 'ProQual Level 3 Certificate in Facial Electrotherapy in London W1: regulated qualification training with hands-on practice in a doctor-led clinic.',
    icon: 'beam',
    tint: 'rgba(150,130,95,.32)',
    img: 'course-facial-electrotherapy.jpg',
    imgAlt: 'Facial electrotherapy training at the LCA Academy',
    about: [
      'Unlike a CPD certificate, this is a <strong>regulated qualification</strong>: the ProQual Level 3 Certificate in Facial Electrotherapy sits on the national qualifications framework, which is exactly why insurers, employers and advanced training providers ask for it by name.',
      'The subject is machine-based facial treatment: microcurrent, galvanic, high frequency and related electrotherapy modalities, taught with the theory, safety and supervised practice a regulated certificate demands.',
      'For many students the greater value is the doorway it opens: Level 3 is the recognised platform from which advanced aesthetic qualifications and treatments become accessible.',
    ],
    coverIntro: 'A regulated syllabus, delivered with clinic-floor practicality.',
    covers: [
      '<strong>Electrotherapy science:</strong> how each modality works on skin and muscle, in usable terms',
      '<strong>Machine treatments in practice:</strong> microcurrent, galvanic, high frequency and steaming',
      '<strong>Skin analysis and treatment planning:</strong> matching modality to skin and goal',
      '<strong>Health, safety and hygiene:</strong> to the standard a regulated qualification requires',
      '<strong>Client care and consultation:</strong> professional practice that survives assessment and reality',
      '<strong>Portfolio and assessment preparation:</strong> evidencing your competence properly',
    ],
    steps: [
      ['Enquire and confirm your route', 'We check your background against the qualification requirements and map any preparation you need before enrolment, honestly and specifically.'],
      ['Structured theory', 'The regulated syllabus, taught for understanding rather than memorisation, with support materials to study between sessions.'],
      ['Supervised practical training', 'Machine treatments practised on live models in our working clinic, building the logged, supervised experience the qualification requires.'],
      ['Assessment and certification', 'Formal assessment against ProQual standards, then your Level 3 certificate, and clear advice on the advanced routes it unlocks.'],
    ],
    accreditation: [
      'The ProQual Level 3 Certificate is a <strong>regulated qualification</strong>, distinct from attendance or CPD certificates, and recognised accordingly by insurers and training providers.',
      'LCA delivers it as a registered clinic and training academy, alongside OFQUAL-regulated study and QUALIFI qualifications at Levels 4, 5 and 7, so your next step is available where you took your last one.',
    ],
    faqs: [
      ['What makes this different from a CPD course?', 'Regulation. CPD certificates document professional development; a regulated Level 3 qualification sits on the national framework and is asked for by name by insurers and advanced course providers.'],
      ['Who should take this qualification?', 'Beauty professionals formalising their status, career changers building a recognised foundation, and anyone whose ambition points toward advanced aesthetics where Level 3 is the expected platform.'],
      ['What happens after Level 3?', 'Doors open: advanced aesthetic training and higher-level qualifications, including the QUALIFI Level 4 to 7 routes we offer, become realistically accessible.'],
      ['Is there formal assessment?', 'Yes; regulated qualifications require it, and we prepare you for it thoroughly. Assessment is a feature here, not a threat: it is what gives the certificate its weight.'],
      ['How do I begin?', 'Enquire with your background via the contact page or email; we will confirm your route onto the qualification personally.'],
    ],
    rail: [
      ['Qualification', 'ProQual Level 3 Certificate, regulated'],
      ['Format', 'Structured theory, supervised practice, assessment'],
      ['Focus', 'Machine-based facial treatments'],
      ['Progression', 'Platform for Level 4+ aesthetics routes'],
      ['Setting', 'Working clinic, 157 Seymour Place, W1'],
    ],
    related: [
      ['academy/ofqual-level-3-diploma.html', 'Alternative route', 'OFQUAL Level 3 Diploma'],
      ['academy/anatomy-physiology.html', 'Underpin it', 'Anatomy & Physiology'],
      ['academy/index.html', 'Overview', 'All courses'],
    ],
    ctaTitle: 'Get the certificate that gets asked for.',
    ctaLede: 'Enquire about the ProQual Level 3 in Facial Electrotherapy and put a regulated qualification behind your practice.',
  },

  {
    slug: 'ofqual-level-3-diploma',
    kickerTag: 'Regulated · OFQUAL Level 3',
    title: 'OFQUAL Level 3 Diploma + CPD Courses',
    lede: 'The combined route: a nationally regulated Level 3 diploma paired with hands-on CPD treatment courses, building recognition and skill in one programme.',
    metaDesc: 'OFQUAL-regulated Level 3 diploma with CPD aesthetic courses in London W1: the combined qualification and skills route at the LCA Academy.',
    icon: 'rosette',
    tint: 'rgba(169,133,59,.36)',
    img: 'course-ofqual-diploma.jpg',
    imgAlt: 'OFQUAL Level 3 diploma training at the LCA Academy',
    about: [
      'Aspiring practitioners usually face a choice: study for a regulated qualification that proves status, or take practical courses that build skill. This programme removes the choice by <strong>combining both</strong>: an OFQUAL-regulated Level 3 diploma alongside CPD treatment courses taught in our clinic.',
      'The diploma provides the nationally recognised foundation that insurers and advanced training providers look for; the CPD courses provide supervised, hands-on competence in real treatments. Finishing with both is precisely the profile the industry now expects.',
      'As with everything at the LCA Academy, practical elements run on live models in a working W1 clinic under the direct supervision of a registered doctor.',
    ],
    coverIntro: 'Two strands, one programme.',
    covers: [
      '<strong>The regulated diploma strand:</strong> anatomy and physiology, skin science, health and safety, and professional practice to OFQUAL-regulated standards',
      '<strong>Formal assessment:</strong> portfolio and assessment preparation, taken seriously and supported',
      '<strong>The CPD skills strand:</strong> hands-on treatment courses selected with us to match your career direction',
      '<strong>Supervised clinical practice:</strong> live-model treatment experience inside a working clinic',
      '<strong>Insurance and compliance literacy:</strong> operating legitimately from day one',
      '<strong>Progression planning:</strong> a mapped route toward Level 4 and beyond, including QUALIFI pathways',
    ],
    steps: [
      ['Enquire and design your programme', 'We assess your background and ambitions, then confirm your diploma route and the CPD courses that best serve it, honestly and specifically.'],
      ['Study the regulated syllabus', 'Structured Level 3 study with support materials and real teaching, built for understanding and for passing formal assessment.'],
      ['Train hands-on', 'Your chosen CPD treatment courses, taught on live models under direct doctor supervision in our Marylebone clinic.'],
      ['Assess, certify, progress', 'Complete your diploma assessment and CPD certifications, and leave with a mapped, realistic progression route toward advanced practice.'],
    ],
    accreditation: [
      'The diploma strand is <strong>OFQUAL-regulated</strong>, placing it on the national qualifications framework that employers, insurers and higher-level training providers recognise by default.',
      'LCA is a registered clinic and training academy also offering QUALIFI qualifications at Levels 4, 5 and 7, which means the progression route you are shown is one we can actually deliver.',
    ],
    faqs: [
      ['Why combine a diploma with CPD courses?', 'Because each alone is half a profile. The regulated diploma proves recognised status; CPD courses prove treatment skill. Together they read exactly the way insurers, employers and clients want.'],
      ['I have no background in aesthetics. Is this for me?', 'This is the route designed for exactly that starting point: a regulated foundation plus supervised practical skills, sequenced sensibly. Enquire and we will map your version of it.'],
      ['How is the programme paced?', 'Around study and supervised practice that respect working lives; exact structure and scheduling are confirmed at enquiry so the commitment is clear before you enrol.'],
      ['What does it lead to?', 'Legitimate, insurable Level 3 status with practical skills, and a genuine platform for Level 4 to 7 study, including QUALIFI routes we deliver ourselves.'],
      ['How do I start?', 'Send an enquiry via the contact page or email with a little about your background, and we will design your programme with you personally.'],
    ],
    rail: [
      ['Qualification', 'OFQUAL-regulated Level 3 diploma'],
      ['Plus', 'Hands-on CPD treatment courses'],
      ['Format', 'Structured study, supervised practice, assessment'],
      ['Progression', 'Mapped routes to QUALIFI Levels 4 to 7'],
      ['Setting', 'Working clinic, 157 Seymour Place, W1'],
    ],
    related: [
      ['academy/facial-electrotherapy.html', 'Alternative route', 'Facial Electrotherapy · ProQual L3'],
      ['academy/dermal-filler-foundation.html', 'Skills strand', 'Dermal Filler Foundation'],
      ['academy/anatomy-physiology.html', 'Underpin it', 'Anatomy & Physiology'],
    ],
    ctaTitle: 'Status and skill, in one route.',
    ctaLede: 'Enquire about the combined OFQUAL Level 3 and CPD programme, and enter aesthetics with both halves of a credible profile.',
  },

  {
    slug: 'anatomy-physiology',
    kickerTag: 'CPD Course · Foundation Theory',
    title: 'Anatomy & Physiology Course',
    lede: 'The knowledge underneath every safe treatment: skin, muscle, vasculature and systems, taught for practitioners rather than examiners.',
    metaDesc: 'Anatomy and physiology training for aesthetics in London W1: CPD-accredited foundation theory for safe practice and career progression.',
    icon: 'book',
    tint: 'rgba(140,125,100,.30)',
    img: 'course-anatomy-physiology.jpg',
    imgAlt: 'Anatomy and physiology study at the LCA Academy',
    about: [
      'Every confident answer a good practitioner gives, about safety, about risk, about why a treatment works, rests on anatomy and physiology. This course builds that foundation properly, for people who intend to use it rather than merely pass it.',
      'The teaching is unapologetically applied: facial anatomy is taught the way injectors need it, vasculature the way anyone holding a needle must know it, and skin physiology the way skin practitioners actually use it.',
      'It stands alone as essential grounding, and it slots underneath our practical courses and regulated qualifications as the theory strand everything else assumes.',
    ],
    coverIntro: 'The systems that matter to aesthetic practice, taught in practical depth.',
    covers: [
      '<strong>Skin structure and physiology:</strong> layers, function, healing and ageing',
      '<strong>Facial anatomy for practitioners:</strong> muscles, fat compartments and danger zones',
      '<strong>Vascular and nervous systems:</strong> what every injector must map before touching skin',
      '<strong>Circulatory and lymphatic function:</strong> the systems behind IV therapy and recovery',
      '<strong>Infection control fundamentals:</strong> the why behind clinical hygiene, not just the rules',
      '<strong>Applied revision:</strong> anchoring knowledge to the treatments you plan to practise',
    ],
    steps: [
      ['Enquire and set your goal', 'Tell us where your career is heading; we confirm how this course fits your pathway and what to pair it with.'],
      ['Structured study', 'Clear, sequenced teaching with support materials, built for genuine understanding at a working pace.'],
      ['Applied learning', 'Anatomy anchored to real treatments and demonstrations from clinic practice, so knowledge attaches to use.'],
      ['Certification and next steps', 'Complete the course, receive your CPD certificate, and get a mapped recommendation for the practical training it underpins.'],
    ],
    accreditation: [
      'CPD-accredited and delivered by a registered clinic and training academy, with certification recognised as the theory grounding for our practical and regulated routes.',
      'Students frequently pair it with the Dermal Filler Foundation, Phlebotomy or the OFQUAL Level 3 route, and we will happily sequence it for your goal.',
    ],
    faqs: [
      ['Do I need this before practical courses?', 'It depends on your background: healthcare professionals often have it; career changers usually benefit enormously. We advise honestly at enquiry rather than upsell by default.'],
      ['Is it heavy on memorisation?', 'It is taught for understanding and use: anatomy tied to treatments, physiology tied to safety decisions. What you understand, you retain; what you retain, you practise safely with.'],
      ['Is the course clinical or classroom?', 'Structured study enriched with clinic-floor demonstration, since we teach inside a working clinic and use that fact deliberately.'],
      ['Will it help with regulated qualifications?', 'Directly; anatomy and physiology underpin Level 3 and higher study, and this course is designed to slot underneath those routes.'],
      ['How do I enrol?', 'Enquire via the contact page or email with the course name, and we will confirm fit and dates personally.'],
    ],
    rail: [
      ['Level', 'CPD-accredited foundation theory'],
      ['Format', 'Structured study with applied teaching'],
      ['Focus', 'Skin, facial anatomy, vasculature, systems'],
      ['Underpins', 'Practical courses and regulated routes'],
      ['Setting', 'LCA Academy, 157 Seymour Place, W1'],
    ],
    related: [
      ['academy/dermal-filler-foundation.html', 'Build on it', 'Dermal Filler Foundation'],
      ['academy/phlebotomy.html', 'Build on it', 'Phlebotomy Course'],
      ['academy/ofqual-level-3-diploma.html', 'Go regulated', 'OFQUAL Level 3 Diploma'],
    ],
    ctaTitle: 'Know why, before you learn how.',
    ctaLede: 'Enquire about the Anatomy & Physiology course and give every future skill a foundation worth building on.',
  },
];
